spring.application.name=Workshop-Associations
spring.datasource.url=jdbc:mysql://localhost:3306/foyerAssociation-1alt?TimezoneShift=true&createDatabaseIfNotExist=true&useLegauseUnicode=true&useJDBCCompliantcyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8081
server.servlet.context-path=/tpfoyer